TMSolution\DynamicFormBundle\Entity\FormConstraintCategory:
    properties:
        name:
            type: field
            setter: setName
            getter: getName
        formConstraints:
            relation_type: oneToMany
            type: entity
            setter: null
            getter: getFormConstraints
    business: {  }
    views:
        filter:
            - name
            - formConstraints
        list:
            - name
        get:
            - name
        insert:
            - name
        edit:
            - name
        sort:
            - name
        record:
            columns:
                column_1:
                    lines:
                        line_1:
                            - name
                        line_2:
                            - formConstraints
                        line_3: {  }
        typeahead: {  }
        tabs:
            overwrite:
                get: false
                edit: false
                insert: false
            items:
                formConstraints:
                    name: formConstraints
    type: entity
    table: dynamic_form_constraint_category
    field:
        name:
            name: name
            type: string
            length: 4000
            precision: 0
            scale: 0
            unique: false
            nullable: true
            options: {  }
            columnDefinition: null
    id:
        id:
            name: id
            type: integer
            length: null
            precision: 0
            scale: 0
            unique: false
            nullable: false
            options: {  }
            columnDefinition: null
    oneToMany:
        formConstraints:
            mappedBy: FormConstraintCategory
            targetEntity: FormConstraint
            cascade: null
            fetch: LAZY
            orphanRemoval: false
            indexBy: null
            name: formConstraints
            relation_type: oneToMany
            fullNamespace: TMSolution\DynamicFormBundle\Entity\FormConstraint
            alias: form-constraint
