parameters:    
    tm_solution.dynamic_form_bundle.system_form_item_option_value.config: 
        base:   
            services:
                 get:
                        name: 'tm_solution.dynamic_form_bundle.system_form_item_option_value.model'
                        method: findOneById            
        actions:        
            new:
                allowed: true
                templates:
                    widget: 'System\FormItemOptionValue\new.html.twig'
                services:
                    create:
                        name: 'tm_solution.dynamic_form_bundle.system_form_item_option_value.model'
                        method: save
                form: 
                   action: new 
                   form_type: 'TMSolution\DynamicFormBundle\Form\Type\System\FormItemOptionValue\InsertFormType'
                
                template_var: 'formItemOptionValue' 
                adapter: 'app_bundle.data_adapter'
                redirection:
                    route_name: index   
            edit:
                allowed: true
                templates:
                    widget: 'System\FormItemOptionValue\edit.html.twig' 
                form: 
                   form_type: 'TMSolution\DynamicFormBundle\Form\Type\System\FormItemOptionValue\EditFormType' 
                   action: edit
                services:
                    update:
                        name: 'tm_solution.dynamic_form_bundle.system_form_item_option_value.model'
                        method: update
                template_var: 'formItemOptionValue'
                adapter: 'app_bundle.data_adapter'            
            delete:
                allowed: true
                form: 
                   action: delete
                services:
                    delete:
                        name: 'tm_solution.dynamic_form_bundle.system_form_item_option_value.model'
                        method: delete
                redirection:
                    route_name: index        
                templates:
                    widget: 'System\FormItemOptionValue\delete.html.twig'
                adapter: 'app_bundle.data_adapter'            
            index:
                allowed: true
                templates:
                    widget: 'System\FormItemOptionValue\index.html.twig'
                adapter: 'app_bundle.data_adapter'      
            list:
                allowed: 
                    - xhttp
                    - subrequest
                templates:
                    widget: 'System\FormItemOptionValue\list.html.twig' 
                services:
                    list:                        
                        name: 'tm_solution.dynamic_form_bundle.system_form_item_option_value.paginator_model'                        
                        method: find
                form: 
                   form_type: 'TMSolution\DynamicFormBundle\Form\Type\System\FormItemOptionValue\FilterFormType'
                   action: list
                   method: GET
                template_var: 'formItemOptionValues'                
                adapter: 'app_bundle.paginator_data_adapter'    
            typeahead:
                allowed: 
                    - xhttp
                    - subrequest
                templates:
                    widget: 'blank.html.twig' 
                services:
                    list:
                        name: 'tm_solution.dynamic_form_bundle.system_form_item_option_value.typeahead'
                        method: find
                form: 
                   form_type: 'TMSolution\DynamicFormBundle\Form\Type\System\FormItemOptionValue\FilterFormType'
                   action: list
                   method: GET
                adapter: 'flexix_model.typeahead_adapter'   
            filter:
                allowed:
                    - xhttp
                    - subrequest
                templates:
                    widget: 'System\FormItemOptionValue\filter.html.twig' 
                form: 
                   form_type: 'TMSolution\DynamicFormBundle\Form\Type\System\FormItemOptionValue\FilterFormType'
                   method: GET
                   action: index
                adapter: 'app_bundle.data_adapter'            
            get:
                allowed: true
                templates:
                    widget: 'System\FormItemOptionValue\get.html.twig'
                template_var: 'formItemOptionValue'
                adapter: 'app_bundle.data_adapter'            
            tabs:
                allowed: true
                templates:
                    widget: 'System\FormItemOptionValue\tabs.html.twig'
                template_var: 'formItemOptionValue'
                adapter: 'app_bundle.data_adapter'     
            
services:
        tm_solution.dynamic_form_bundle.system_form_item_option_value:
            class: Flexix\ConfigurationBundle\Util\Configuration
            arguments: ['%tm_solution.dynamic_form_bundle.system_form_item_option_value.config%']
            tags:
                - { name: flexix_prototype_controller.controller_configuration, module: 'system', alias: 'form-item-option-value' } 

        tm_solution.dynamic_form_bundle.system_form_item_option_value.form.type.edit:
            class: TMSolution\DynamicFormBundle\Form\Type\System\FormItemOptionValue\EditFormType
            arguments: ['@flexix_prototype_controller.context','@doctrine.orm.entity_manager']
            tags:
                - { name: form.type }
        
        tm_solution.dynamic_form_bundle.system_form_item_option_value.form.type.insert:
            class: TMSolution\DynamicFormBundle\Form\Type\System\FormItemOptionValue\InsertFormType
            arguments: ['@flexix_prototype_controller.context','@doctrine.orm.entity_manager']
            tags:
                - { name: form.type }        
        
        tm_solution.dynamic_form_bundle.system_form_item_option_value.form.type.filter:
            class: TMSolution\DynamicFormBundle\Form\Type\System\FormItemOptionValue\FilterFormType
            arguments: ['@flexix_prototype_controller.context','@doctrine.orm.entity_manager']
            tags:
                - { name: form.type }            
        tm_solution.dynamic_form_bundle.system_form_item_option_value.model:
            class: TMSolution\DynamicFormBundle\Model\System\FormItemOptionValue\Model
            arguments: ['@doctrine.orm.entity_manager',tm_solution.dynamic_form_bundle.system_form_item_option_value.repository ]
      
        tm_solution.dynamic_form_bundle.system_form_item_option_value.paginator_model:    
            class: TMSolution\DynamicFormBundle\Model\System\FormItemOptionValue\PaginatorModel
            arguments: ['@flexix_model.model','@flexix_model.filter','@flexix_model.paginator',null,'@knp_paginator.subscriber.sliding_pagination','@tm_solution.dynamic_form_bundle.system_form_item_option_value.repository','%locale%']   
                
        tm_solution.dynamic_form_bundle.system_form_item_option_value.repository:    
            class: TMSolution\DynamicFormBundle\Repository\System\FormItemOptionValue\Repository
            arguments: ['@doctrine.orm.entity_manager','@tm_solution.dynamic_form_bundle.system_form_item_option_value.metadata','%locale%']   
            
        tm_solution.dynamic_form_bundle.system_form_item_option_value.metadata:    
            class: Doctrine\ORM\Mapping\ClassMetaData
            arguments: [TMSolution\DynamicFormBundle\Entity\FormItemOptionValue]            
        tm_solution.dynamic_form_bundle.system_form_item_option_value.typeahead:
            class: TMSolution\DynamicFormBundle\Model\System\FormItemOptionValue\Typeahead
            arguments: ['@tm_solution.dynamic_form_bundle.system_form_item_option_value.model','@flexix_model.filter','@flexix_model.paginator', {'sort': 'entity.id', 'sortDirection':'asc'},'@knp_paginator.subscriber.sliding_pagination','@tm_solution.dynamic_form_bundle.system_form_item_option_value.repository','%locale%','query',[ 'entity.value']]    
    
            
            
           
